module.exports = {
  content: ['./index.html', './js/**/*.js'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#3b304a',
        'inverse-primary': '#6a5f00',
        'primary-fixed-dim': '#dec800',
        outline: '#979177',
        'on-secondary-container': '#d6a4ff',
        'on-tertiary-fixed': '#001f24',
        'tertiary-fixed': '#9cf0ff',
        tertiary: '#ffffff',
        primary: '#ffffff',
        'on-error': '#690005',
        'surface-container-high': '#30253f',
        background: '#180e27',
        'surface-container-lowest': '#130921',
        'on-surface-variant': '#cdc7aa',
        'on-tertiary-container': '#006f7c',
        'primary-container': '#fde400',
        'secondary-fixed': '#f1daff',
        'error-container': '#93000a',
        'on-primary': '#373100',
        'tertiary-container': '#9cf0ff',
        'surface-bright': '#40344f',
        'secondary-fixed-dim': '#dfb7ff',
        'surface-container': '#251b34',
        surface: '#180e27',
        'inverse-surface': '#eddcfe',
        'on-tertiary': '#00363d',
        'on-secondary-fixed-variant': '#642498',
        error: '#ffb4ab',
        'inverse-on-surface': '#362b45',
        'on-secondary': '#4b007e',
        'surface-variant': '#3b304a',
        secondary: '#dfb7ff',
        'tertiary-fixed-dim': '#00daf3',
        'surface-tint': '#dec800',
        'on-primary-fixed': '#201c00',
        'surface-dim': '#180e27',
        'on-surface': '#eddcfe',
        'secondary-container': '#67279b',
        'on-secondary-fixed': '#2d004f',
        'on-background': '#eddcfe',
        'on-primary-fixed-variant': '#504700',
        'on-primary-container': '#716500',
        'on-tertiary-fixed-variant': '#004f58',
        'on-error-container': '#ffdad6',
        'surface-container-low': '#21172f',
        'outline-variant': '#4b4731',
        'primary-fixed': '#fde400',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        margin: '1rem',
        'space-xs': '0.25rem',
        'space-lg': '1.25rem',
        'space-md': '0.75rem',
        gutter: '1rem',
        'space-sm': '0.5rem',
        'space-xl': '2rem',
      },
      fontFamily: {
        'label-lg': ['Space Grotesk'],
        'label-md': ['Space Grotesk'],
        'headline-lg': ['Anybody'],
        'body-lg': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Anybody'],
        'body-md': ['Plus Jakarta Sans'],
        'headline-md': ['Anybody'],
        'body-sm': ['Plus Jakarta Sans'],
        'headline-xl': ['Anybody'],
        'label-sm': ['Space Grotesk'],
        'headline-xl-mobile': ['Anybody'],
      },
      fontSize: {
        'label-lg': ['14px', { lineHeight: '18px', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '36px', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '26px', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '30px', fontWeight: '700' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-xl': ['40px', { lineHeight: '44px', fontWeight: '800' }],
        'label-sm': ['10px', { lineHeight: '12px', fontWeight: '700' }],
        'headline-xl-mobile': ['32px', { lineHeight: '36px', fontWeight: '800' }],
      },
    },
  },
};
